### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by AIisCool** [Jaded-Encoding-Thaumaturgy/vapoursynth-reconstruct#1]
`Python exception: Failed to load C:\VapourSynth\Plugins\recon.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.`

Also, do I just use: `clip = core.recon(clip=clip)` ?

**Comment by Setsugennoao** [comment]
You're missing some god-knows-what vsredist, you should just install all.

Example usage can be found here https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise/blob/master/vsdenoise/regress.py#L547-L573
